- id: '1580055766826'
  alias: BUTTON - Double Click - Disable Bathroom Auto-off
  description: ''
  trigger:
  - device_id: 65be4690c6514242bc9a25a68ccb1658
    domain: zha
    platform: device
    subtype: remote_button_double_press
    type: remote_button_double_press
  condition: []
  action:
  - entity_id: automation.turn_off_bathroom_lights
    service: automation.toggle
- id: '1580352501547'
  alias: AWAY - turn off lights
  description: ''
  trigger:
  - entity_id: device_tracker.slyphone
    event: leave
    platform: zone
    zone: zone.home
  condition: []
  action:
  - entity_id: script.turn_off_all_lights
    service: script.turn_on
- id: '1580704464732'
  alias: Set custom theme on startup
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: slate
    service: frontend.set_theme
- id: '1580848497127'
  alias: BUTTON - Click - Toggle Lightstrip
  description: ''
  trigger:
  - device_id: 65be4690c6514242bc9a25a68ccb1658
    domain: zha
    platform: device
    subtype: remote_button_short_press
    type: remote_button_short_press
  condition: []
  action:
  - entity_id: light.philips_lightstrip
    service: light.toggle
- id: '1580945524186'
  alias: BUTTON - Long Press - SOS
  description: ''
  trigger:
  - device_id: 65be4690c6514242bc9a25a68ccb1658
    domain: zha
    platform: device
    subtype: remote_button_long_press
    type: remote_button_long_press
  condition: []
  action:
  - data:
      message: SEND HELP.... sly
      title: help
    service: notify.email_notifications
