
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
shopping_list:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret hass_url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Enable themes
frontend:
  themes: !include_dir_merge_named themes

# Grouped Lights (better here than groups YAML)
light:
  - platform: group
    name: Bathroom Lights
    entities:
        - light.philips_bathroom_bulb_1
        - light.philips_bathroom_bulb_2
  - platform: group
    name: Second Bathroom Lights
    entities:
        - light.philips_bathroom_bulb_3
        - light.philips_bathroom_bulb_4
   
  
# Text to speech
tts:
  - platform: google_translate
    base_url: !secret base_url_tts

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

# Z Wave
zwave:
  network_key: !secret zwave_network_key
  
# SOS email - temp
notify:
  - name: email_notifications
    platform: smtp
    server: !secret email_server
    port: !secret email_port
    sender: !secret email_sender
    encryption: starttls
    username: !secret email_username
    password: !secret email_pw
    recipient:
      - !secret email_receiver1
      - !secret email_receiver2
    sender_name: SOS from Sly
    
# August
august:
  login_method: email
  username: !secret august_username
  password: !secret august_pw

# Nest
badnest:
  issue_token: !secret issue_token
  cookie: !secret cookie
  region: us
climate:
  - platform: badnest
    scan_interval: 10
 
# Custom sensors
sensor:
    # RPi stats
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use
      - type: memory_use_percent
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: processor_use
  - platform: command_line
    name: CPU Temperature
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(1) }}'
    # Sunset based floorplan bg color
  - platform: template
    sensors:
      sun_brightness:
        friendly_name: "Sun Brightness"
        value_template: >-
          {% if state_attr('sun.sun', 'elevation') > 20  %}
            bright
          {% elif state_attr('sun.sun', 'elevation') > 9 %}
            mid    
          {% elif state_attr('sun.sun', 'elevation') > -3 %}
            dark                
          {% else %}
            black
          {% endif %} 